### PR TITLE
25 rubocop

### PR DESCRIPTION
**Pull request by piyushtiw**

### CODE REVIEW

**Comment by piyushtiw** [comment]
@vipulnsward _a

**Comment by vipulnsward** [comment]
Please resolve conflicts.

**Comment by vipulnsward** [comment]
@piyushtiw _a

**Comment by piyushtiw** [comment]
@vipulnsward _a

**Comment by piyushtiw** [comment]
refer to https://github.com/bigbinary/acehelp/pull/36

**Pull request closed without merging**
