### PR TITLE
Do not hard-code URLs in the Elm code

### PR DESCRIPTION
**Pull request by vishaltelangre**
Fixes https://github.com/bigbinary/acehelp/issues/737.

### CODE REVIEW

**Comment by vishaltelangre** [comment]
@tejaswinichile _a Please review. The frontend (widget app, especially) does not care about what the app URL is. We pass an "app_url" flag to the Elm app while it initializes.

**Comment by tejaswinichile** [comment]
@vishaltelangre This LGTM 👍  Please merge after resolving the conflicts.
https://monosnap.com/file/pBaQ59IX0i0NbSzm7hdswdHmmiQZuh checked on deployed heroku app.

**Comment by tejaswinichile** [comment]
https://monosnap.com/file/VjZ10i26lokdSKLhor5rlcNeWp0Ss1 @vishaltelangre  Can you take care of this. Check if the URLs are correct for sign-out.

**Comment by vishaltelangre** [comment]
@tejaswinichile Fixed the logout link issue.

**Pull request merged**
