### PR TITLE
seed data for all tables

### PR DESCRIPTION
**Pull request by piyushtiw**

### CODE REVIEW

**Comment by neerajdotname** [comment]
@piyushtiw assign this PR to me when it's ready. I'll merge and will run the rake task on staging so that new data shows up over there.

**Comment by piyushtiw** [comment]
@neerajdotname _a

**Comment by neerajdotname** [comment]
This is for future. If data is changed again then

1. merge the PR
2. Visit https://dashboard.heroku.com/apps/acehelp-staging/activity and ensure that latest code is deployed. Wait for 30 seconds for the deployment to finish.
3. Execute `heroku run rake setup_sample_data -a acehelp-staging ` to repopulate sample data.

**Comment by neerajdotname** [comment]
I have executed the rake task. Please check if data is properly populated or not and the api is working or not.

**Pull request merged**
