### PR TITLE
sign in after sign up

### PR DESCRIPTION
**Pull request by tejaswinichile**
Issue #534

### CODE REVIEW

**Comment by neerajdotname** [comment]
Please stop putting issue number in the PR title.

https://monosnap.com/file/5Oqb1WM4lnyYkAc7wtj3S3BmG1JOYz

**Comment by tejaswinichile** [comment]
@prathamesh-sonpatki _a Please check.

**Comment by prathamesh-sonpatki** [comment]
Code looks okey but I am not able to create organization because user_id is getting hit to nil somehow after sign up.

@tejaswinichile _A We need to add tests to make sure that user_id is present on the page and is not blank.

**Comment by tejaswinichile** [comment]
@prathamesh-sonpatki _a Please check. The tests which you have mentioned needs ELM side test cases. I have created issue #543 to handle the same.

**Pull request merged**
