### PR TITLE
update login arch

### PR DESCRIPTION
**Pull request by abdul-shajin**

### CODE REVIEW

**Comment by tejaswinichile** [comment]
@abdul-shajin _a Please resolve conflicts.

**Comment by breezyboa** [comment]
@tejaswinichile _a elm side changes are done the tokens will be passed on each/most requests and will be updated with each response

**Comment by tejaswinichile** [comment]
@neerajdotname _a Can you review this.

**Comment by neerajdotname** [comment]
@tejaswinichile Ping me when you can to discuss this PR.

**Comment by tejaswinichile** [comment]
Closing this PR, As raising new with cookies flow and PR review comments.
Issue #490

**Pull request closed without merging**
