### PR TITLE
Login Page in Elm

### PR DESCRIPTION
**Pull request by breezyboa**
#302

### CODE REVIEW

**Comment by breezyboa** [comment]
@sudeeptarlekar _a can you please review

**Comment by neerajdotname** [comment]
@breezyboa What kind of work you are assigning Sudeep to review ? Does he need to look at both elm and Rails code or just the Rails code ? Sudeep is working on another project so slowly we need to take him out of this project.

**Comment by breezyboa** [comment]
@neerajdotname Its elm code. 
@tejaswinichile _a can also review this.

**Comment by tejaswinichile** [comment]
@breezyboa _a Please check conflicts.

**Comment by tejaswinichile** [comment]
LGTM 👍

**Pull request merged**
