### PR TITLE
Hamburger Menu

### PR DESCRIPTION
**Pull request by ritesh404**
#563

### CODE REVIEW

**Comment by ritesh404** [comment]
@tejaswinichile _a can you please review the elm code

**Comment by ritesh404** [comment]
@ritesh404 _a assigning it back to me to add the "Add New Organization" button

**Comment by ritesh404** [comment]
@tejaswinichile _a please review

**Comment by tejaswinichile** [comment]
When we change the organization from the hamburger and try to reload then the default organization gets loaded.
But in case of when we change the organization then do some action and the try to reload then it works fine.
finding: when we switch the organization URL is not updating right away.
@ritesh404 _a Please check.

**Comment by ritesh404** [comment]
@tejaswinichile _a please check now. Also please rebase with master

**Pull request merged**
