### PR TITLE
suggested page no url match

### PR DESCRIPTION
**Pull request by piyushtiw**

### CODE REVIEW

**Comment by piyushtiw** [comment]
@vipulnsward _a

**Comment by vipulnsward** [comment]
No, we should instead ask users to "visit" all articles?

@breezyboa _a probably something to be handled on ELM side?

**Comment by breezyboa** [comment]
@vipulnsward can be handled in Elm.
Do you think it will be better to Auto redirect to All if we get a 400 bad request on suggested articles?

**Comment by vipulnsward** [comment]
Hmm, we can't do that, we always have the suggested articles tab.
Lets implement showing user a "No suggested article" or something and guiding them to look at "All articles" page

We can discuss more what feels better after this is implemented.

**Comment by vipulnsward** [comment]
@breezyboa _a

**Comment by breezyboa** [comment]
Assigning it to @piyushtiw _a

**Comment by piyushtiw** [comment]
refer to https://github.com/bigbinary/acehelp/pull/144

**Pull request closed without merging**
