### PR TITLE
team create issue

### PR DESCRIPTION
**Pull request by tejaswinichile**
We are facing logout issue, that user needs to click twice when logging out.
Fixing this might fix the issue that context is not able to find current_user.

### CODE REVIEW

**Comment by tejaswinichile** [comment]
@prathamesh-sonpatki _a Please check

**Comment by prathamesh-sonpatki** [comment]
@tejaswinichile _A Please add controller level tests for this.

**Comment by tejaswinichile** [comment]
@prathamesh-sonpatki _a Please have a look. I have added this on master but it's not failing.

**Comment by tejaswinichile** [comment]
This PR is no more required as issue got fixed by `force_ssl = true` config changes.
https://github.com/bigbinary/acehelp/commit/bb488dd8f009b713175b67caaa31e566c7f16805

**Pull request closed without merging**
