### PR TITLE
toggle ticket

### PR DESCRIPTION
**Pull request by tejaswinichile**
Issue #328

### CODE REVIEW

**Comment by tejaswinichile** [comment]
@breezyboa _a

**Comment by breezyboa** [comment]
@rishimohan _a can you check the styles

**Comment by rishimohan** [comment]
LGTM @breezyboa _a please merge.

**Comment by tejaswinichile** [comment]
@breezyboa merging this for elm code we are going to handle UI fixes in #400 assigned to @rishimohan

**Pull request merged**
