### PR TITLE
Fix for new organization creation

### PR DESCRIPTION
**Pull request by tejaswinichile**
Issue #450 
1. set error to nil after successful rendering of article list on api key
2. set organization association dependent destroy

### CODE REVIEW

**Comment by tejaswinichile** [comment]
@breezyboa _a please check

**Comment by breezyboa** [comment]
@tejaswinichile _a the error is still flashed for less than a second and then goes off. 
Also, note that the organization name is also not displayed on top right.

The question is why does the error happen in the first place when it clearly should not

**Comment by tejaswinichile** [comment]
When we are creating new org we do not have any api-key present, then we send another request to check any available organization associated to the user.

**Comment by tejaswinichile** [comment]
@breezyboa _a can you look into this as https://github.com/bigbinary/acehelp/pull/453/files#diff-2bc8a2b43c1b3cd65e5916c2e7338445R722 not making any change, we need to set orgKey to ReaderCmd,  which is not happening immediately after organization creation and it's sending apiKey nil to article list first request.

**Comment by breezyboa** [comment]
@tejaswinichile okay ill have a look

**Pull request merged**
