### PR TITLE
category page stayling

### PR DESCRIPTION
**Pull request by piyushtiw**

### CODE REVIEW

**Comment by vipulnsward** [comment]
@rishimohan _a I think you already did this in some other PR?

**Comment by rishimohan** [comment]
@vipulnsward Nope, this PR adds icon to the links in Library tag. 

@piyushtiw _a Lets replace this icon with folder icon which would be more relevant to Category. Search for "folder" in the cheatsheet here https://fontawesome.com/cheatsheet

**Comment by piyushtiw** [comment]
@rishimohan _a Please review it.

**Comment by rishimohan** [comment]
@piyushtiw From now on, please assign all UI related changes to me in case review is needed.

**Pull request merged**
