### PR TITLE
Get rid of devise auth token gem

### PR DESCRIPTION
**Pull request by tejaswinichile**
Issue #503 
1. removed devise token auth
2. maintaining user in session variables
3. updated graphQL controller accordingly
4. removed devise_token_auth inclusion

### CODE REVIEW

**Comment by tejaswinichile** [comment]
@prathamesh-sonpatki Have a look at this PR. We don't need devise-token-auth to override. After sign in, now we are just storing the `current_user` into session. Need your suggestion on same.
As if we want to use another gem to validate user we are gonna need to store the current_user in session

**Comment by prathamesh-sonpatki** [comment]
@neerajdotname We had a discussion about this and decided to go with using just warden with devise for authentication. 

@tejaswinichile is currently working on that. Right now the app is working fine on master branch and this PR will just get rid of the extra gem and simplify the process.

**Comment by prathamesh-sonpatki** [comment]
@tejaswinichile _A

**Comment by tejaswinichile** [comment]
@prathamesh-sonpatki _a Please have a look at this PR.

**Comment by prathamesh-sonpatki** [comment]
Code looks good. I was testing the app on heroku and ran into this issue: https://monosnap.com/file/fZRgDEXdzysSWzbkvxpID7javOByh5

Looks like something wrong with the heroku sample data.

**Comment by tejaswinichile** [comment]
This error should have been thrown >> https://monosnap.com/file/JcpaPNA2iskw135ILEpTz2qd5yZWNI
Checking issue .

**Comment by tejaswinichile** [comment]
@prathamesh-sonpatki _a Please check we have removed devise_token_auth related columns.

**Comment by tejaswinichile** [comment]
@ritesh404 _a Please have a look at elm changes.

**Comment by prathamesh-sonpatki** [comment]
@tejaswinichile @neerajdotname Verified the code and the app and it is working well.

**Comment by tejaswinichile** [comment]
Merging this code to master.

**Pull request merged**
