### PR TITLE
Redirect user to sign_in after sign_up

### PR DESCRIPTION
**Pull request by tejaswinichile**
1. updated main model to accept token to set after login
2. added login response after successfull login
3. updated session login page to hook Elm pages to sign in

Issue #448 #458

### CODE REVIEW

**Comment by tejaswinichile** [comment]
- [ ]  redirect to login page after successful sign-up
- [ ]  redirect to organization page after login response
- [ ]  curent_user check and handle every request with auth token

**Comment by tejaswinichile** [comment]
@breezyboa _a Please check but do not merge, as now we don't have current_user set in the system after login with authentication token this breaks after page refresh.
We need to handle this case after we merge #435

**Comment by breezyboa** [comment]
@tejaswinichile _a please resolve conflicts

**Comment by tejaswinichile** [comment]
Handled this in https://github.com/bigbinary/acehelp/pull/435/commits/7bce985130c17b04f2ce95e7948bc1a27c43bcd3

closing this PR.

**Pull request closed without merging**
