### PR TITLE
60 screens for adminland

### PR DESCRIPTION
**Pull request by sudeeptarlekar**
This PR is for #60 
Only added HTML layout in this PR. Submit actions are not implemented. Will raise PRs in batch so as to ease review process.

@neerajdotname _a Please review. There will be much scope for improvements.

### CODE REVIEW

**Comment by neerajdotname** [comment]
Please assign it to Ritesh for review.

**Comment by sudeeptarlekar** [comment]
@breezyboa _a Please review PR.

**Comment by breezyboa** [comment]
@sudeeptarlekar adminland should be a separate Elm app all together. It should not be mixed with the current Widget codebase. We will need to create a separate entry point for this app

**Comment by sudeeptarlekar** [comment]
Closing this PR as it is invalid now. @sudeeptarlekar _a

**Pull request closed without merging**
